id: IA7676717
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:18:32+00:00'
last_modified: '2022-06-08T09:57:17.028894+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3372
  title: ཐོན་མིའི་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3FCC:
      image_group_id: I3CN3523
      title: ''
      total_pages: 364
      order: 1
      base_file: 3FCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
