id: P009288
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3372
  title: ཐོན་མིའི་ཞལ་ལུང་།
  author: ''
  volumes:
    f9c7b948aff8473b81c857ad29fcecea:
      image_group_id: I3CN3523
      title: ''
      volume_number: 1
      total_pages: 364
